export interface GalleryVideoItem {
  id: string;
  title: string;
  category: "skin" | "hair" | "antiaging" | "laser" | "procedure";
  categoryLabel: string;
  duration: string;
  driveFileId: string;
  driveEmbedUrl: string;
  driveViewUrl: string;
  doctor: string;
  description: string;
  badge: string;
  poster: string;
}

export interface GalleryPhotoItem {
  id: string;
  title: string;
  category: "all" | "skin" | "hair" | "antiaging" | "laser" | "clinic";
  categoryLabel: string;
  src: string;
  timeline?: string;
  details: string;
  doctorTag?: string;
}

export const GALLERY_VIDEOS: GalleryVideoItem[] = [
  {
    id: "video-1",
    title: "Precision Laser Rejuvenation & Facial Dermatology",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    duration: "1:45 min",
    driveFileId: "1sjuNZ4OaRdQ7EXj9_MCvO79z3g1kMvRH",
    driveEmbedUrl: "https://drive.google.com/file/d/1sjuNZ4OaRdQ7EXj9_MCvO79z3g1kMvRH/preview",
    driveViewUrl: "https://drive.google.com/file/d/1sjuNZ4OaRdQ7EXj9_MCvO79z3g1kMvRH/view?usp=sharing",
    doctor: "Dr. Ana (Dr. Ananya Sharma)",
    description: "Watch the step-by-step clinical laser therapy and dermoscopy execution inside our sterilized procedure suite.",
    badge: "Featured Procedure",
    poster: "/images/gallery/Screenshot 2026-09-17 152109.png",
  },
  {
    id: "video-2",
    title: "Medical Medi-Facial & Deep Barrier Infusion Protocol",
    category: "skin",
    categoryLabel: "Aesthetic Dermatology",
    duration: "2:10 min",
    driveFileId: "1bVVzVaWhFiHG8aCT7d0qi309APaO5XSd",
    driveEmbedUrl: "https://drive.google.com/file/d/1bVVzVaWhFiHG8aCT7d0qi309APaO5XSd/preview",
    driveViewUrl: "https://drive.google.com/file/d/1bVVzVaWhFiHG8aCT7d0qi309APaO5XSd/view?usp=sharing",
    doctor: "Dr. Ana (Dr. Ananya Sharma)",
    description: "High-magnification pore cleansing, oxygen therapy, and dermatological serum penetration for instant glass-skin radiance.",
    badge: "Skin Glow Session",
    poster: "/images/gallery/Screenshot 2026-09-17 150045.png",
  },
  {
    id: "video-3",
    title: "Bio-FUE Hair Restoration & GFC Scalp Protocol",
    category: "hair",
    categoryLabel: "Hair Restoration",
    duration: "3:05 min",
    driveFileId: "1rxWontDZJ7quRSrpFZ5UaEWqRQ5Uro5P",
    driveEmbedUrl: "https://drive.google.com/file/d/1rxWontDZJ7quRSrpFZ5UaEWqRQ5Uro5P/preview",
    driveViewUrl: "https://drive.google.com/file/d/1rxWontDZJ7quRSrpFZ5UaEWqRQ5Uro5P/view?usp=sharing",
    doctor: "Dr. Rohit Verma",
    description: "Detailed micro-graft extraction and density placement ensuring 100% natural hairline angle and maximum graft survival.",
    badge: "Microsurgical Tour",
    poster: "/images/gallery/Screenshot 2026-09-17 150928.png",
  },
  {
    id: "video-4",
    title: "Acne Scar Resurfacing & Fractional Subcision",
    category: "skin",
    categoryLabel: "Laser Resurfacing",
    duration: "2:30 min",
    driveFileId: "1mvapljwGcJr2Jb4jAxEUr5_5_lXc0N7m",
    driveEmbedUrl: "https://drive.google.com/file/d/1mvapljwGcJr2Jb4jAxEUr5_5_lXc0N7m/preview",
    driveViewUrl: "https://drive.google.com/file/d/1mvapljwGcJr2Jb4jAxEUr5_5_lXc0N7m/view?usp=sharing",
    doctor: "Dr. Ana (Dr. Ananya Sharma)",
    description: "Targeted fractional CO2 laser ablation coupled with subcision for deep boxcar and rolling acne scar correction.",
    badge: "Scar Revision",
    poster: "/images/gallery/Screenshot 2026-09-17 150413.png",
  },
  {
    id: "video-5",
    title: "Anti-Aging Facial Sculpting & Collagen Rejuvenation",
    category: "antiaging",
    categoryLabel: "Anti-Aging & Aesthetics",
    duration: "2:00 min",
    driveFileId: "1x5Xnbvpat_arJv21_P9nw93os8LB1hH7",
    driveEmbedUrl: "https://drive.google.com/file/d/1x5Xnbvpat_arJv21_P9nw93os8LB1hH7/preview",
    driveViewUrl: "https://drive.google.com/file/d/1x5Xnbvpat_arJv21_P9nw93os8LB1hH7/view?usp=sharing",
    doctor: "Dr. Priya Saxena",
    description: "Non-surgical facial lifting, neuromodulator smoothing, and natural dermal volume restoration.",
    badge: "Aesthetic Sculpture",
    poster: "/images/gallery/Screenshot 2026-09-17 151012.png",
  },
];

export const GALLERY_PHOTOS: GalleryPhotoItem[] = [
  {
    id: "photo-1",
    title: "Severe Acne & Erythema Laser Revision",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 145940.png",
    timeline: "4 Sessions (12 Weeks)",
    details: "Significant reduction of active inflammatory papules and smoothing of skin texture under certified medical protocol.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-2",
    title: "Bio-FUE Hairline Reconstruction & Crown Density",
    category: "hair",
    categoryLabel: "Hair Restoration",
    src: "/images/gallery/Screenshot 2026-09-17 150045.png",
    timeline: "6 Months Post-Op",
    details: "3,200 grafts implanted with natural angulation and 3 supportive sessions of autologous GFC growth factors.",
    doctorTag: "Dr. Rohit Verma",
  },
  {
    id: "photo-3",
    title: "Under-Eye Melasma & Pigmentary Correction",
    category: "skin",
    categoryLabel: "Pigmentation & Laser",
    src: "/images/gallery/Screenshot 2026-09-17 150115.png",
    timeline: "8 Weeks Protocol",
    details: "Targeted Q-switched laser toning paired with medical depigmenting actives to clear recalcitrant melasma.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-4",
    title: "Non-Surgical Midface Lift & Dermal Contour",
    category: "antiaging",
    categoryLabel: "Anti-Aging & Aesthetics",
    src: "/images/gallery/Screenshot 2026-09-17 150236.png",
    timeline: "Immediate Outcome",
    details: "US-FDA approved hyaluronic acid filler micro-droplet injection restoring youthful cheek volume and jawline definition.",
    doctorTag: "Dr. Priya Saxena",
  },
  {
    id: "photo-5",
    title: "Vitiligo (Safed Dag) Targeted Phototherapy",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 150305.png",
    timeline: "5 Months Medical Protocol",
    details: "Repigmentation of depigmented patches using targeted excimer therapy and immunomodulators.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-6",
    title: "Permanent Laser Hair Reduction (Face & Neck)",
    category: "laser",
    categoryLabel: "Medical Lasers",
    src: "/images/gallery/Screenshot 2026-09-17 150330.png",
    timeline: "6 Sessions Course",
    details: "Triple-wavelength diode laser with active sapphire contact cooling for pain-free permanent follicle elimination.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-7",
    title: "Deep Boxcar & Icepick Scar Subcision",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 150413.png",
    timeline: "3 Sessions",
    details: "Surgical subcision breaking fibrotic tethering followed by fractional CO2 collagen stimulation.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-8",
    title: "Beard Transplant & Jawline Density Design",
    category: "hair",
    categoryLabel: "Hair Restoration",
    src: "/images/gallery/Screenshot 2026-09-17 150449.png",
    timeline: "4 Months Post-Op",
    details: "Precision single-hair graft harvesting and sharp jawline contouring for fuller facial beard growth.",
    doctorTag: "Dr. Rohit Verma",
  },
  {
    id: "photo-9",
    title: "Periorbital Fine Lines & Wrinkle Laser Treatment",
    category: "antiaging",
    categoryLabel: "Anti-Aging",
    src: "/images/gallery/Screenshot 2026-09-17 150524.png",
    timeline: "3 Sessions",
    details: "Fractional non-ablative resurfacing stimulating dermal elastin and erasing stubborn crow's feet.",
    doctorTag: "Dr. Priya Saxena",
  },
  {
    id: "photo-10",
    title: "Exilis Ultra Double Chin & Submental Contouring",
    category: "antiaging",
    categoryLabel: "Body & Facial Contouring",
    src: "/images/gallery/Screenshot 2026-09-17 150621.png",
    timeline: "4 Sessions (6 Weeks)",
    details: "Simultaneous radiofrequency and ultrasound energy tightening skin laxity and sculpting a sharp jawline.",
    doctorTag: "Dr. Priya Saxena",
  },
  {
    id: "photo-11",
    title: "Laser Tattoo & Pigment Removal",
    category: "laser",
    categoryLabel: "Medical Lasers",
    src: "/images/gallery/Screenshot 2026-09-17 150712.png",
    timeline: "5 Sessions Course",
    details: "High-peak picosecond laser shattering ink pigments without causing thermal scarring to surrounding skin.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-12",
    title: "Luxury Clinical Suite & Medical Infrastructure",
    category: "clinic",
    categoryLabel: "Clinic Atmosphere",
    src: "/images/gallery/Screenshot 2026-09-17 150809.png",
    timeline: "Golf City, Lucknow",
    details: "State-of-the-art sterile surgical suites, German diagnostic equipment, and private VIP consultation rooms.",
    doctorTag: "Ewa Derma Clinic",
  },
  {
    id: "photo-13",
    title: "Clinical Phototherapy & Dermatology Suite",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 150844.png",
    timeline: "Verified Case",
    details: "Specialized dermatological session for inflammatory skin revision and tone restoration.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-14",
    title: "Advanced Trichology & Hairline Density",
    category: "hair",
    categoryLabel: "Hair Restoration",
    src: "/images/gallery/Screenshot 2026-09-17 150928.png",
    timeline: "5 Months Post-Op",
    details: "High-density graft placement and follicle activation with regenerative PRP infusion.",
    doctorTag: "Dr. Rohit Verma",
  },
  {
    id: "photo-15",
    title: "Facial Sculpting & Dermal Contouring",
    category: "antiaging",
    categoryLabel: "Anti-Aging & Aesthetics",
    src: "/images/gallery/Screenshot 2026-09-17 151012.png",
    timeline: "Immediate Result",
    details: "Harmonized aesthetic lifting and collagen stimulation for youthful facial symmetry.",
    doctorTag: "Dr. Priya Saxena",
  },
  {
    id: "photo-16",
    title: "Medical Laser Resurfacing & Tone Correction",
    category: "laser",
    categoryLabel: "Medical Lasers",
    src: "/images/gallery/Screenshot 2026-09-17 151058.png",
    timeline: "4 Sessions",
    details: "Targeted laser toning delivering clear, smooth, and radiant skin texture.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-17",
    title: "Acne Scar Revision & Texture Smoothing",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 151215.png",
    timeline: "8 Weeks Protocol",
    details: "Combination peeling and collagen remodeling therapy for clear skin.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-18",
    title: "Crown Density & Hair Regrowth Protocol",
    category: "hair",
    categoryLabel: "Hair Restoration",
    src: "/images/gallery/Screenshot 2026-09-17 151357.png",
    timeline: "6 Months Protocol",
    details: "GFC growth factor therapy and medical follicle preservation.",
    doctorTag: "Dr. Rohit Verma",
  },
  {
    id: "photo-19",
    title: "In-Clinic Consultation Suite & Diagnostics",
    category: "clinic",
    categoryLabel: "Clinic Atmosphere",
    src: "/images/gallery/Screenshot 2026-09-17 151423.png",
    timeline: "Golf City Suite",
    details: "Private consultation room with multi-spectrum skin diagnostics.",
    doctorTag: "Ewa Derma Clinic",
  },
  {
    id: "photo-20",
    title: "Precision Laser Hair Removal Protocol",
    category: "laser",
    categoryLabel: "Medical Lasers",
    src: "/images/gallery/Screenshot 2026-09-17 151501.png",
    timeline: "6 Sessions",
    details: "Triple wavelength cooling laser for flawless hair reduction.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-21",
    title: "Aesthetic Anti-Aging & Jawline Definition",
    category: "antiaging",
    categoryLabel: "Anti-Aging",
    src: "/images/gallery/Screenshot 2026-09-17 151645.png",
    timeline: "Immediate Post-Op",
    details: "Micro-droplet hyaluronic contouring and RF skin tightening.",
    doctorTag: "Dr. Priya Saxena",
  },
  {
    id: "photo-22",
    title: "Pigmentation & Sun Damage Clearance",
    category: "skin",
    categoryLabel: "Clinical Dermatology",
    src: "/images/gallery/Screenshot 2026-09-17 151719.png",
    timeline: "6 Weeks Protocol",
    details: "Targeted pigment clearing and barrier reinforcement protocol.",
    doctorTag: "Dr. Ana",
  },
  {
    id: "photo-23",
    title: "Sterile Operating Suite & Micro-Surgery",
    category: "clinic",
    categoryLabel: "Clinic Atmosphere",
    src: "/images/gallery/Screenshot 2026-09-17 151740.png",
    timeline: "Surgical Theatre",
    details: "International standard surgical facility with HEPA airflow filtration.",
    doctorTag: "Ewa Derma Clinic",
  },
  {
    id: "photo-24",
    title: "Follicular Unit Extraction Density Outcome",
    category: "hair",
    categoryLabel: "Hair Restoration",
    src: "/images/gallery/Screenshot 2026-09-17 151834.png",
    timeline: "9 Months Post-Op",
    details: "Complete crown and hairline restoration with high graft survival.",
    doctorTag: "Dr. Rohit Verma",
  },
];

// Curated sliding marquee stream arrays
export const MARQUEE_ROW_1 = [
  "/images/gallery/Screenshot 2026-09-17 150844.png",
  "/images/gallery/Screenshot 2026-09-17 150928.png",
  "/images/gallery/Screenshot 2026-09-17 151012.png",
  "/images/gallery/Screenshot 2026-09-17 151058.png",
  "/images/gallery/Screenshot 2026-09-17 151215.png",
  "/images/gallery/Screenshot 2026-09-17 151357.png",
  "/images/gallery/Screenshot 2026-09-17 151423.png",
  "/images/gallery/Screenshot 2026-09-17 151501.png",
  "/images/gallery/Screenshot 2026-09-17 151645.png",
  "/images/gallery/Screenshot 2026-09-17 151719.png",
  "/images/gallery/Screenshot 2026-09-17 151740.png",
  "/images/gallery/Screenshot 2026-09-17 151834.png",
];

export const MARQUEE_ROW_2 = [
  "/images/gallery/Screenshot 2026-09-17 151905.png",
  "/images/gallery/Screenshot 2026-09-17 151935.png",
  "/images/gallery/Screenshot 2026-09-17 151953.png",
  "/images/gallery/Screenshot 2026-09-17 152005.png",
  "/images/gallery/Screenshot 2026-09-17 152037.png",
  "/images/gallery/Screenshot 2026-09-17 152109.png",
  "/images/gallery/Screenshot 2026-09-17 152125.png",
  "/images/gallery/Screenshot 2026-09-17 152145.png",
  "/images/gallery/Screenshot 2026-09-17 152205.png",
  "/images/gallery/Screenshot 2026-09-17 152238.png",
  "/images/gallery/Screenshot 2026-09-17 152257.png",
  "/images/gallery/Screenshot 2026-09-17 152342.png",
  "/images/gallery/Screenshot 2026-09-17 152430.png",
  "/images/gallery/Screenshot 2026-09-17 152525.png",
];
